-- NOGOON SUVARGA: customer accounts + order tracking
-- Run this in Supabase SQL Editor once.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  order_code text not null unique,
  tree_type text not null,
  quantity integer not null default 1 check (quantity > 0),
  tree_only_price_mnt bigint not null default 0 check (tree_only_price_mnt >= 0),
  planting_price_mnt bigint not null default 0 check (planting_price_mnt >= 0),
  maintenance_price_mnt bigint not null default 0 check (maintenance_price_mnt >= 0),
  total_price_mnt bigint not null default 0 check (total_price_mnt >= 0),
  location text not null default 'Бага модны ам',
  dedication_name text,
  dedication_text text,
  status text not null default 'pending_payment',
  progress_step integer not null default 1 check (progress_step between 1 and 5),
  payment_method text not null default 'bank_transfer',
  payment_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  progress_step integer not null check (progress_step between 1 and 5),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.tree_records (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  tree_id text unique,
  planted_at date,
  photo_url text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists order_events_order_id_idx on public.order_events(order_id);

alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_events enable row level security;
alter table public.tree_records enable row level security;

-- Customers can only read/update their own profile.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);

-- Customers can see their own orders, but cannot alter order status/pricing from the browser.
drop policy if exists "orders_select_own" on public.orders;
create policy "orders_select_own" on public.orders for select using (auth.uid() = user_id);
drop policy if exists "orders_insert_own" on public.orders;
create policy "orders_insert_own" on public.orders for insert with check (auth.uid() = user_id);

-- Order progress is staff-managed; customers are read-only here.
drop policy if exists "order_events_select_own" on public.order_events;
create policy "order_events_select_own" on public.order_events for select using (
  exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
);

drop policy if exists "tree_records_select_own" on public.tree_records;
create policy "tree_records_select_own" on public.tree_records for select using (
  exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
);

-- Automatically create a profile for every new authenticated customer.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Keep updated_at current.
create or replace function public.touch_order_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at
before update on public.orders
for each row execute procedure public.touch_order_updated_at();
